name: Flutter Build for Android Apk with Docker

on: [ workflow_dispatch ]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ppbymrtk/flutter:0.1.0.android
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Dependencies
        run: flutter pub get
      - name: Analyze
        run: flutter analyze
      - name: Build
        run: flutter build apk --release
#        run: flutter build apk --release --split-per-abi
      - name: Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build
          path: build/